In [1]:
# import relevant rdkit objects
from rdkit.Chem import RDKFingerprint, SDMolSupplier

# create instance of sdf reader
suppl = SDMolSupplier('baru.sdf')

# read all molecules besides ones with errors into a list
mols = [mol for mol in suppl if mol is not None]

# calculate fingerprints
fps = [RDKFingerprint(mol) for mol in mols]

In [2]:
fps

In [5]:
import numpy as np
fps=np.array(fps)
print (fps)

[[0 0 0 ... 0 0 0]
 [1 0 0 ... 1 1 0]
 [1 1 1 ... 1 0 1]
 ...
 [1 0 1 ... 0 1 1]
 [0 1 0 ... 0 1 1]
 [0 1 0 ... 0 1 1]]
